// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"x-ui/database"
	"x-ui/database/repository"
	"x-ui/web/service"
)

import (
	_ "x-ui/database"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	db := database.GetDBProvider()
	settingRepository := repository.NewSettingRepository(db)
	settingService := service.NewSettingService(settingRepository)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository, settingService)
	outboundRepository := repository.NewOutboundRepository(db)
	outboundService := service.NewOutboundService(outboundRepository)
	inboundRepository := repository.NewInboundRepository(db)
	clientTrafficRepository := repository.NewClientTrafficRepository(db)
	clientIPRepository := repository.NewClientIPRepository(db)
	xrayAPI := service.NewXrayAPI()
	inboundService := service.NewInboundService(inboundRepository, clientTrafficRepository, clientIPRepository, xrayAPI)
	xrayService := service.NewXrayService(settingService, xrayAPI)
	serverService := service.NewServerService()
	status := service.NewStatus()
	tgbot := service.NewTgBot(inboundService, settingService, serverService, xrayService, status)
	app := NewApp(settingService, userService, outboundService, inboundService, xrayService, serverService, tgbot, status, xrayAPI, inboundRepository, outboundRepository, settingRepository, userRepository)
	return app, nil
}
