// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"x-ui/database"
	"x-ui/database/repository"
)

import (
	_ "x-ui/database"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	db := database.GetDBProvider()
	inboundRepository := repository.NewInboundRepository(db)
	outboundRepository := repository.NewOutboundRepository(db)
	settingRepository := repository.NewSettingRepository(db)
	userRepository := repository.NewUserRepository(db)
	app := NewApp(inboundRepository, outboundRepository, settingRepository, userRepository)
	return app, nil
}
