# NilAway as a golangci-lint plugin
# Requires golangci-lint >= v1.57.0
version: v1.59.0
plugins:
  - module: "go.uber.org/nilaway"
    import: "go.uber.org/nilaway/cmd/gclplugin"
    version: latest
