# golangci-lint v2 configuration
# Reference: https://golangci-lint.run/docs/plugins/module-plugins/
version: "2"

run:
  tests: false
  timeout: 5m
  skip-dirs:
    - test_scripts

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - nilaway  # NilAway: Uber's nil pointer detector (via custom plugin)

  settings:
    custom:
      nilaway:
        type: "module"
        description: Static analysis tool to detect potential nil panics in Go code.
        settings:
          include-pkgs: "x-ui"

issues: {}
