# golangci-lint v2 configuration
# Reference: https://golangci-lint.run/docs/configuration/
version: "2"

run:
  tests: false
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

  exclusions:
    paths:
      - test_scripts

issues: {}
